# appveyor file

# build version format
version: "{build}"

platform: 
  - x64
  - x86

image: Visual Studio 2017

# Set a known clone folder
clone_folder: c:\p

# fix lineendings in Windows
init:
  - git config --global core.autocrlf input
  - git config --global user.name "Thiago Lugli"
  - git config --global user.email thiagoelg@gmail.com

environment: 
  UTO:
    secure: x7hTGMqkrEgGiJOYv8dDmwXfey7rYHQ6IlRPF7y9PY3Xyj6WxMOEvxQrAMY53DdE

matrix:
  fast_finish: true

install:
  - ps: Install-Product node 14 $env:PLATFORM
  - cmd: SET PATH=c:\python27;%PATH%
  - cmd: SET JOBS=4
  - cmd: SET BUILD_ONLY=true
  - cmd: npm ci --build-from-source
  - cmd: if %PLATFORM% EQU x86 (SET TP=ia32) else (set TP=x64)
  - cmd: npx prebuild --strip -r electron --all --arch %TP% -u %UTO%
  - cmd: npx prebuild --strip -r node-webkit --all --arch %TP% -u %UTO%
  - cmd: npx prebuild --strip --all --arch %TP% -u %UTO%
test_script:
  - node --version
  - npm --version

build: off

branches:
  only:
    - master

cache:
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.node-gyp'